server:
  port: 8585
  servlet:
    context-path: /sisuz/api/v1

spring:
  profiles:
    active: dev

---
#Development profile
spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SISUZ_WEB
    password: S1@suz16
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle10gDialect
  mail:
    host: smtp.mailtrap.io
    port: 25
    protocol: smtp
    username: b4d8e81581b941
    password: 09433e5f0ed773
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false